language: java
script: mvn -DseleniumDriverClass=org.openqa.selenium.phantomjs.PhantomJSDriver test

after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && { python addServer.py; mvn -DskipTests deploy --settings ~/.m2/mySettings.xml; };"
